/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaproject.Console.db;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import myException.SoldOut;
import java.io.*;

/**
 *
 * @author yas se
 */
public class Menu extends javax.swing.JFrame {

    Pan p2 = new Pan();
    Pan p1 = new Pan(new Mixer("small", "dish"), new PizzaType("Marinara"), 9);
    PizzaLogger l=new PizzaLogger();
    static DataBase db = new DataBase();
    WriteInFile write=new WriteInFile();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1 = new javax.swing.ButtonGroup();
        g2 = new javax.swing.ButtonGroup();
        g3 = new javax.swing.ButtonGroup();
        g4 = new javax.swing.ButtonGroup();
        g5 = new javax.swing.ButtonGroup();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        c1 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        sizeBox = new javax.swing.JPanel();
        smallBox = new javax.swing.JRadioButton();
        mediumBox = new javax.swing.JRadioButton();
        largeBox = new javax.swing.JRadioButton();
        marinaraBox = new javax.swing.JRadioButton();
        mamamiaBox = new javax.swing.JRadioButton();
        vegBox = new javax.swing.JRadioButton();
        marBox = new javax.swing.JRadioButton();
        cipBox = new javax.swing.JRadioButton();
        l6 = new javax.swing.JLabel();
        chicken = new javax.swing.JRadioButton();
        c6 = new javax.swing.JButton();
        PizaaBox = new javax.swing.JPanel();
        picPanBox = new javax.swing.JLabel();
        picDishBox = new javax.swing.JLabel();
        dishBox = new javax.swing.JRadioButton();
        panBox = new javax.swing.JRadioButton();
        SliceBox = new javax.swing.JPanel();
        sliceCh = new javax.swing.JComboBox<>();
        sliceMessage = new javax.swing.JLabel();
        drinksBox = new javax.swing.JPanel();
        d = new javax.swing.JPanel();
        drinksMessage = new javax.swing.JLabel();
        yesBox = new javax.swing.JRadioButton();
        noBox = new javax.swing.JRadioButton();
        svn = new javax.swing.JLabel();
        mir = new javax.swing.JLabel();
        cola = new javax.swing.JLabel();
        d1 = new javax.swing.JRadioButton();
        d2 = new javax.swing.JRadioButton();
        d3 = new javax.swing.JRadioButton();
        addDrinks = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        OrderBott = new javax.swing.JButton();
        InformationBott = new javax.swing.JButton();
        homeBott = new javax.swing.JButton();
        exitBott = new javax.swing.JButton();
        exitBott1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(869, 23, -1, -1));

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/marinara.jpg"))); // NOI18N
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 196, -1));

        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/margharita.jpg"))); // NOI18N
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 196, 160));

        l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Chicken-Pizza_exps30800_FM143298B03_11_8bC_RMS-9.jpg"))); // NOI18N
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 200, 160));

        l7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/veg.jpg"))); // NOI18N
        getContentPane().add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 192, -1));

        l8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mama mia.jpg"))); // NOI18N
        getContentPane().add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 192, -1));

        c1.setText("Contents");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        c4.setText("Contents");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, -1, -1));

        c2.setText("Contents");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        c3.setText("Contents");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        c5.setText("Contents");
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, -1, -1));

        sizeBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Pizza Size"));
        sizeBox.setEnabled(false);

        g2.add(smallBox);
        smallBox.setText("small");
        smallBox.setEnabled(false);
        smallBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallBoxActionPerformed(evt);
            }
        });

        g2.add(mediumBox);
        mediumBox.setText("medium");
        mediumBox.setEnabled(false);
        mediumBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumBoxActionPerformed(evt);
            }
        });

        g2.add(largeBox);
        largeBox.setText("large");
        largeBox.setEnabled(false);
        largeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sizeBoxLayout = new javax.swing.GroupLayout(sizeBox);
        sizeBox.setLayout(sizeBoxLayout);
        sizeBoxLayout.setHorizontalGroup(
            sizeBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sizeBoxLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(smallBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(mediumBox)
                .addGap(107, 107, 107)
                .addComponent(largeBox)
                .addGap(50, 50, 50))
        );
        sizeBoxLayout.setVerticalGroup(
            sizeBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sizeBoxLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(sizeBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallBox)
                    .addComponent(mediumBox)
                    .addComponent(largeBox))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(sizeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 470, 80));

        g1.add(marinaraBox);
        marinaraBox.setText("Marinara");
        marinaraBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marinaraBoxActionPerformed(evt);
            }
        });
        getContentPane().add(marinaraBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        g1.add(mamamiaBox);
        mamamiaBox.setText("Mamamia");
        mamamiaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mamamiaBoxActionPerformed(evt);
            }
        });
        getContentPane().add(mamamiaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        g1.add(vegBox);
        vegBox.setText("Vegetables");
        vegBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegBoxActionPerformed(evt);
            }
        });
        getContentPane().add(vegBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        g1.add(marBox);
        marBox.setText("Margharita");
        marBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marBoxActionPerformed(evt);
            }
        });
        getContentPane().add(marBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, -1));

        g1.add(cipBox);
        cipBox.setText("Cipolla");
        cipBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipBoxActionPerformed(evt);
            }
        });
        getContentPane().add(cipBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 180, -1, -1));

        l6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cipolla.jpg"))); // NOI18N
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 196, 160));

        g1.add(chicken);
        chicken.setText("Chicken");
        chicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenActionPerformed(evt);
            }
        });
        getContentPane().add(chicken, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, -1, -1));

        c6.setText("Contents");
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        getContentPane().add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 210, -1, -1));

        PizaaBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Pizza Deep"));
        PizaaBox.setEnabled(false);

        picPanBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pan.jpg"))); // NOI18N
        picPanBox.setText("jLabel2");
        picPanBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        picPanBox.setEnabled(false);

        picDishBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dish.jpg"))); // NOI18N
        picDishBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        picDishBox.setEnabled(false);

        g3.add(dishBox);
        dishBox.setText("dish");
        dishBox.setEnabled(false);
        dishBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dishBoxActionPerformed(evt);
            }
        });

        g3.add(panBox);
        panBox.setText("pan");
        panBox.setEnabled(false);
        panBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PizaaBoxLayout = new javax.swing.GroupLayout(PizaaBox);
        PizaaBox.setLayout(PizaaBoxLayout);
        PizaaBoxLayout.setHorizontalGroup(
            PizaaBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PizaaBoxLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(picDishBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(picPanBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PizaaBoxLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(dishBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panBox)
                .addGap(92, 92, 92))
        );
        PizaaBoxLayout.setVerticalGroup(
            PizaaBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PizaaBoxLayout.createSequentialGroup()
                .addGroup(PizaaBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PizaaBoxLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(panBox))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PizaaBoxLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dishBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PizaaBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(picDishBox, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picPanBox))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(PizaaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 470, -1));

        SliceBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Slices"));
        SliceBox.setEnabled(false);

        sliceCh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "6", "8", "10" }));
        sliceCh.setEnabled(false);
        sliceCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sliceChActionPerformed(evt);
            }
        });

        sliceMessage.setText("How many slices do you want your pizza to be?");
        sliceMessage.setEnabled(false);

        javax.swing.GroupLayout SliceBoxLayout = new javax.swing.GroupLayout(SliceBox);
        SliceBox.setLayout(SliceBoxLayout);
        SliceBoxLayout.setHorizontalGroup(
            SliceBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SliceBoxLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(SliceBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliceMessage)
                    .addComponent(sliceCh, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        SliceBoxLayout.setVerticalGroup(
            SliceBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SliceBoxLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(sliceMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliceCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(SliceBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 470, 120));

        drinksBox.setBorder(javax.swing.BorderFactory.createTitledBorder("drinks"));
        drinksBox.setEnabled(false);

        d.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        drinksMessage.setText("Do you want to order a drink ?");
        drinksMessage.setEnabled(false);

        g4.add(yesBox);
        yesBox.setText("Yes");
        yesBox.setEnabled(false);
        yesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBoxActionPerformed(evt);
            }
        });

        g4.add(noBox);
        noBox.setText("No");
        noBox.setEnabled(false);
        noBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dLayout = new javax.swing.GroupLayout(d);
        d.setLayout(dLayout);
        dLayout.setHorizontalGroup(
            dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dLayout.createSequentialGroup()
                .addGroup(dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(yesBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noBox))
                    .addGroup(dLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(drinksMessage)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dLayout.setVerticalGroup(
            dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drinksMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesBox)
                    .addComponent(noBox))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        svn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/7.jpeg"))); // NOI18N
        svn.setEnabled(false);

        mir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mirinda-2006.jpg"))); // NOI18N
        mir.setEnabled(false);

        cola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cola.jpg"))); // NOI18N
        cola.setEnabled(false);

        g5.add(d1);
        d1.setText("Coca Cola");
        d1.setEnabled(false);

        g5.add(d2);
        d2.setText("7 Up");
        d2.setEnabled(false);

        g5.add(d3);
        d3.setText("Mirinda");
        d3.setEnabled(false);

        addDrinks.setText("Add the drink to Order list");
        addDrinks.setEnabled(false);
        addDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrinksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout drinksBoxLayout = new javax.swing.GroupLayout(drinksBox);
        drinksBox.setLayout(drinksBoxLayout);
        drinksBoxLayout.setHorizontalGroup(
            drinksBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksBoxLayout.createSequentialGroup()
                .addGroup(drinksBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drinksBoxLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drinksBoxLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(cola, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(drinksBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addDrinks)
                            .addGroup(drinksBoxLayout.createSequentialGroup()
                                .addComponent(svn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mir)))))
                .addContainerGap())
            .addGroup(drinksBoxLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(d1)
                .addGap(112, 112, 112)
                .addComponent(d2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(d3)
                .addGap(46, 46, 46))
        );
        drinksBoxLayout.setVerticalGroup(
            drinksBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksBoxLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(drinksBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(svn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drinksBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d1)
                    .addComponent(d2)
                    .addComponent(d3))
                .addGap(37, 37, 37)
                .addComponent(addDrinks)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        getContentPane().add(drinksBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 510, 450));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Odrer"));

        OrderBott.setText("Order pizza");
        OrderBott.setEnabled(false);
        OrderBott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderBottActionPerformed(evt);
            }
        });

        InformationBott.setText("Information about the pizza you ordered");
        InformationBott.setEnabled(false);
        InformationBott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformationBottActionPerformed(evt);
            }
        });

        homeBott.setText("Another Order ?");
        homeBott.setEnabled(false);
        homeBott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBottActionPerformed(evt);
            }
        });

        exitBott.setText("Exit");
        exitBott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBottActionPerformed(evt);
            }
        });

        exitBott1.setText("Back Home");
        exitBott1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBott1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(exitBott, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitBott1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(homeBott, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OrderBott, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InformationBott, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(OrderBott)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InformationBott)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeBott)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBott)
                    .addComponent(exitBott1))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 250, 250, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliceChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sliceChActionPerformed
        drinksBox.setEnabled(true);
        drinksMessage.setEnabled(true);
        yesBox.setEnabled(true);
        noBox.setEnabled(true);
    }//GEN-LAST:event_sliceChActionPerformed

    private void OrderBottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderBottActionPerformed
        InformationBott.setEnabled(true);

        String type;
        String size;
        String deep;
        String slice;
        int sliceInt;
        if (marinaraBox.isSelected()) {
            type = marinaraBox.getText();
        } else if (mamamiaBox.isSelected()) {
            type = mamamiaBox.getText();
        } else if (vegBox.isSelected()) {
            type = vegBox.getText();
        } else if (marBox.isSelected()) {
            type = marBox.getText();
        } else if (chicken.isSelected()) {
            type = chicken.getText();
        } else {
            type = cipBox.getText();
        }

        if (smallBox.isSelected()) {
            size = smallBox.getText();
        } else if (mediumBox.isSelected()) {
            size = mediumBox.getText();
        } else {
            size = largeBox.getText();
        }
        if (dishBox.isSelected()) {
            deep = dishBox.getText();
        } else {
            deep = panBox.getText();
        }
        slice = sliceCh.getSelectedItem().toString();
        sliceInt = Integer.parseInt(slice);
        p1.getDough().setDough_size(size);
        p1.getDough().setDeep(deep);
        p1.getPizzaType().setType(type);
        p1.getPizzaType().setM(p1.getDough());

        p1.setSlice(sliceInt);

        p2 = p1;

        try {
            p1.MakePizza();
            write.PutDataInFile(p1.getPizzaType().getType(), p1.getDough().getSize(), p1.getDough().getDeep(), p1.getCalories());
            
            JOptionPane.showMessageDialog(null, "Your Pizza price is " + PizzaType.price + "$ \n" + "Your Drink price is " + PizzaType.price2 + "$ \n" + "Your final bill is " + (PizzaType.price + PizzaType.price2)
                    + "$ \n"
                    + "Please enter the required amount to complete the process \n"
                    + "Note: You can pay by Visa");
            JOptionPane.showMessageDialog(null, "Your pizza has been successfully ordered ^-^ \n Please wait five minutes to get into the oven \n"
            );

        } catch (HeadlessException | SoldOut ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        /*try
        {
            db.post(p1.getPizzaType().getType(),p1.getDough().getSize(),p1.getDough().getDeep(),p1.getCalories());
        }
        catch (Exception ex) {
            System.out.println(ex.getMessage());
        }*/
        OrderBott.setEnabled(false);
        disE();
        homeBott.setEnabled(true);
        l.log(Messages.LOG_SELECT_PIZZA+p1.getPizzaType().getType());
        l.log(Messages.LOG_SIZE_DEEP+ p1.getDough().getSize()+","+p1.getDough().getDeep());
        l.log(Messages.LOG_SLICE_INPUT+" "+p1.getSlice());


    }//GEN-LAST:event_OrderBottActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        JOptionPane.showMessageDialog(null, "Marinara Pizza contains : \n Marinara suace \n garlic \n olive_oil \n basil \n oregano");
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        JOptionPane.showMessageDialog(null, "Mamamia Pizza contains : \n Tomato_sauce \n mozzarella \n onion \n corn \n peppers \n tuna");
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        JOptionPane.showMessageDialog(null, "Vegetables Pizza contains : \n Tomato_sauce \n mozzarella \n mashroom \n corn \n peppers \n olive");
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        JOptionPane.showMessageDialog(null, " Margharita Pizza contains : \n Tomato_sauce \n mozzarella \n olive");
    }//GEN-LAST:event_c4ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        JOptionPane.showMessageDialog(null, "Chicken Pizza contains : \n Chiken \n mozzarella \n  Parmesan  \n garlic");
    }//GEN-LAST:event_c5ActionPerformed

    private void InformationBottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformationBottActionPerformed
        JOptionPane.showMessageDialog(null, Messages.PIZZA_NAME + p2.getPizzaType().getType() + '\n' + Messages.PIZZA_SIZE_AND_DEEP + p2.getDough().getSize() + "," + p2.getDough().getDeep() + '\n' + Messages.CALORIES_INFO + p2.getCalories() + "\n" + "your Pizza calories is each Slice is :" + p2.getSliceCalories() + "\nyour Pizza Ingredients is :" + Topping.getIngredientsInfo());
        Topping.topping.clear();
        Pan.sum = 0;
        Pan.sum2 = 0;

    }//GEN-LAST:event_InformationBottActionPerformed

    private void mamamiaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mamamiaBoxActionPerformed
        sizeBox.setEnabled(true);
        smallBox.setEnabled(true);
        mediumBox.setEnabled(true);
        largeBox.setEnabled(true);
    }//GEN-LAST:event_mamamiaBoxActionPerformed

    private void marinaraBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marinaraBoxActionPerformed
        sizeBox.setEnabled(true);
        smallBox.setEnabled(true);
        mediumBox.setEnabled(true);
        largeBox.setEnabled(true);

    }//GEN-LAST:event_marinaraBoxActionPerformed

    private void vegBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegBoxActionPerformed
        sizeBox.setEnabled(true);
        smallBox.setEnabled(true);
        mediumBox.setEnabled(true);
        largeBox.setEnabled(true);
    }//GEN-LAST:event_vegBoxActionPerformed

    private void marBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marBoxActionPerformed
        sizeBox.setEnabled(true);
        smallBox.setEnabled(true);
        mediumBox.setEnabled(true);
        largeBox.setEnabled(true);
    }//GEN-LAST:event_marBoxActionPerformed

    private void cipBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipBoxActionPerformed
        sizeBox.setEnabled(true);
        smallBox.setEnabled(true);
        mediumBox.setEnabled(true);
        largeBox.setEnabled(true);
    }//GEN-LAST:event_cipBoxActionPerformed

    private void smallBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallBoxActionPerformed
        PizaaBox.setEnabled(true);
        dishBox.setEnabled(true);
        panBox.setEnabled(true);
        picDishBox.setEnabled(true);
        picPanBox.setEnabled(true);
    }//GEN-LAST:event_smallBoxActionPerformed

    private void mediumBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumBoxActionPerformed
        PizaaBox.setEnabled(true);
        dishBox.setEnabled(true);
        panBox.setEnabled(true);
        picDishBox.setEnabled(true);
        picPanBox.setEnabled(true);
    }//GEN-LAST:event_mediumBoxActionPerformed

    private void largeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeBoxActionPerformed
        PizaaBox.setEnabled(true);
        dishBox.setEnabled(true);
        panBox.setEnabled(true);
        picDishBox.setEnabled(true);
        picPanBox.setEnabled(true);
    }//GEN-LAST:event_largeBoxActionPerformed

    private void dishBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dishBoxActionPerformed
        SliceBox.setEnabled(true);
        sliceMessage.setEnabled(true);
        sliceCh.setEnabled(true);
    }//GEN-LAST:event_dishBoxActionPerformed

    private void panBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panBoxActionPerformed
        SliceBox.setEnabled(true);
        sliceMessage.setEnabled(true);
        sliceCh.setEnabled(true);
    }//GEN-LAST:event_panBoxActionPerformed

    private void exitBottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBottActionPerformed
        this.setVisible(false);
        l.log("Exit");
    }//GEN-LAST:event_exitBottActionPerformed

    private void homeBottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBottActionPerformed
        setE();
        l.log("New Order");
        OrderBott.setEnabled(false);
        g1.clearSelection();
        g2.clearSelection();
        g3.clearSelection();
        g4.clearSelection();
        g5.clearSelection();
        Topping.topping.clear();
        Pan.sum = 0;
        Pan.sum2 = 0;
        PizzaType.price2 = 0;
        homeBott.setEnabled(false);
    }//GEN-LAST:event_homeBottActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        JOptionPane.showMessageDialog(null, "Cipolla Pizza contains :  \n Tomato_sauce \n mozzarella \n onion \n oregano");
    }//GEN-LAST:event_c6ActionPerformed

    private void chickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenActionPerformed
        sizeBox.setEnabled(true);
        smallBox.setEnabled(true);
        mediumBox.setEnabled(true);
        largeBox.setEnabled(true);
    }//GEN-LAST:event_chickenActionPerformed

    private void exitBott1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBott1ActionPerformed
        PizzaJFrame p = new PizzaJFrame();
        p.setVisible(true);
        this.setVisible(false);
      
    }//GEN-LAST:event_exitBott1ActionPerformed

    private void yesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBoxActionPerformed
        cola.setEnabled(true);
        svn.setEnabled(true);
        mir.setEnabled(true);
        d1.setEnabled(true);
        d2.setEnabled(true);
        d3.setEnabled(true);
        addDrinks.setEnabled(true);
        noBox.setEnabled(false);
    }//GEN-LAST:event_yesBoxActionPerformed

    private void noBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBoxActionPerformed
        OrderBott.setEnabled(true);
        yesBox.setEnabled(false);
    }//GEN-LAST:event_noBoxActionPerformed

    private void addDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrinksActionPerformed
        OrderBott.setEnabled(true);
        PizzaType.price2 = 2;
        l.log(Messages.LOG_DRINK);
        JOptionPane.showMessageDialog(null, "The drink has been selected successfully");
    }//GEN-LAST:event_addDrinksActionPerformed

    public void disE() {
        marinaraBox.setEnabled(false);
        chicken.setEnabled(false);
        mamamiaBox.setEnabled(false);
        vegBox.setEnabled(false);
        marBox.setEnabled(false);
        cipBox.setEnabled(false);
        c1.setEnabled(false);
        c2.setEnabled(false);
        c3.setEnabled(false);
        c4.setEnabled(false);
        c5.setEnabled(false);
        c6.setEnabled(false);
        sizeBox.setEnabled(false);
        smallBox.setEnabled(false);
        mediumBox.setEnabled(false);
        largeBox.setEnabled(false);
        PizaaBox.setEnabled(false);
        dishBox.setEnabled(false);
        panBox.setEnabled(false);
        picDishBox.setEnabled(false);
        picPanBox.setEnabled(false);

        SliceBox.setEnabled(false);
        sliceMessage.setEnabled(false);
        sliceCh.setEnabled(false);
        drinksBox.setEnabled(false);
        drinksMessage.setEnabled(false);
        yesBox.setEnabled(false);
        noBox.setEnabled(false);
        d1.setEnabled(false);
        d2.setEnabled(false);
        d3.setEnabled(false);
        cola.setEnabled(false);
        svn.setEnabled(false);
        mir.setEnabled(false);
        addDrinks.setEnabled(false);
    }

    public void setE() {
        marinaraBox.setEnabled(true);
        chicken.setEnabled(true);
        mamamiaBox.setEnabled(true);
        vegBox.setEnabled(true);
        marBox.setEnabled(true);
        cipBox.setEnabled(true);
        c1.setEnabled(true);
        c2.setEnabled(true);
        c3.setEnabled(true);
        c4.setEnabled(true);
        c5.setEnabled(true);
        c6.setEnabled(true);
        /*sizeBox.setEnabled(true);
        smallBox.setEnabled(true);
        mediumBox.setEnabled(true);
        largeBox.setEnabled(true);
        PizaaBox.setEnabled(true);
        dishBox.setEnabled(true);
        panBox.setEnabled(true);
        picDishBox.setEnabled(true);
        picPanBox.setEnabled(true);
        BoxNoName.setEnabled(true);
        SliceBox.setEnabled(true);
        sliceMessage.setEnabled(true);
        sliceCh.setEnabled(true);
         */
        OrderBott.setEnabled(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    public void i() {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InformationBott;
    private javax.swing.JButton OrderBott;
    private javax.swing.JPanel PizaaBox;
    private javax.swing.JPanel SliceBox;
    private javax.swing.JButton addDrinks;
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JRadioButton chicken;
    private javax.swing.JRadioButton cipBox;
    private javax.swing.JLabel cola;
    private javax.swing.JPanel d;
    private javax.swing.JRadioButton d1;
    private javax.swing.JRadioButton d2;
    private javax.swing.JRadioButton d3;
    private javax.swing.JRadioButton dishBox;
    private javax.swing.JPanel drinksBox;
    private javax.swing.JLabel drinksMessage;
    private javax.swing.JButton exitBott;
    private javax.swing.JButton exitBott1;
    private javax.swing.ButtonGroup g1;
    private javax.swing.ButtonGroup g2;
    private javax.swing.ButtonGroup g3;
    private javax.swing.ButtonGroup g4;
    private javax.swing.ButtonGroup g5;
    private javax.swing.JButton homeBott;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JRadioButton largeBox;
    private javax.swing.JRadioButton mamamiaBox;
    private javax.swing.JRadioButton marBox;
    private javax.swing.JRadioButton marinaraBox;
    private javax.swing.JRadioButton mediumBox;
    private javax.swing.JLabel mir;
    private javax.swing.JRadioButton noBox;
    private javax.swing.JRadioButton panBox;
    private javax.swing.JLabel picDishBox;
    private javax.swing.JLabel picPanBox;
    private javax.swing.JPanel sizeBox;
    private javax.swing.JComboBox<String> sliceCh;
    private javax.swing.JLabel sliceMessage;
    private javax.swing.JRadioButton smallBox;
    private javax.swing.JLabel svn;
    private javax.swing.JRadioButton vegBox;
    private javax.swing.JRadioButton yesBox;
    // End of variables declaration//GEN-END:variables
}
